[package]
name = "virtio-queue-ser"
version = "0.14.0"
authors = ["rust-vmm AWS maintainers <rust-vmm-maintainers@amazon.com>"]
description = "Serialization for virtio queue state"
repository.workspace = true
keywords = ["queue", "serialization", "versioning"]
readme = "README.md"
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

[dependencies]
serde = { version = "1.0.27", features = ["derive"] }
virtio-queue = { workspace = true }
vm-memory = { workspace = true }

[dev-dependencies]
virtio-queue = { workspace = true, features = ["test-utils"] }
